package cn.itcast.bos.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-08-19T19:17:41.020+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "IOrderRemoteServiceService", 
                  wsdlLocation = "http://localhost:8080/bos_management_web/services/order?wsdl",
                  targetNamespace = "http://service.bos.itcast.cn/") 
public class IOrderRemoteServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.bos.itcast.cn/", "IOrderRemoteServiceService");
    public final static QName IOrderRemoteServicePort = new QName("http://service.bos.itcast.cn/", "IOrderRemoteServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/bos_management_web/services/order?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IOrderRemoteServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/bos_management_web/services/order?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IOrderRemoteServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IOrderRemoteServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IOrderRemoteServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IOrderRemoteServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IOrderRemoteServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IOrderRemoteServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IOrderRemoteService
     */
    @WebEndpoint(name = "IOrderRemoteServicePort")
    public IOrderRemoteService getIOrderRemoteServicePort() {
        return super.getPort(IOrderRemoteServicePort, IOrderRemoteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOrderRemoteService
     */
    @WebEndpoint(name = "IOrderRemoteServicePort")
    public IOrderRemoteService getIOrderRemoteServicePort(WebServiceFeature... features) {
        return super.getPort(IOrderRemoteServicePort, IOrderRemoteService.class, features);
    }

}
